<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6">
    <h3>Standard-Modul</h3>
        <p>Das Standard Modul ermöglicht es unterschiedliche Inhaltskomponenten in einem wählbaren Raster zu verwalten.</p>
    </div>
    <div class="col-lg-6">
        <h3>Verfügbare Komponenten</h3>
        <ul>
          <li>Überschrift</li>
          <li>Text (Editor: MarkItUp / Redactor 2)</li>
          <li>Downloads</li>
          <li>Film (extern)</li>
          <li>Link (intern / extern)</li>
        </ul>
    </div>
  </div>

</div>
