<div class="container-fluid">
  <div class="row">
    <div class="col-lg-7">
    <h3>Standard-Modul</h3>
        <p>Das Standard Modul ermöglicht es unterschiedliche Inhaltskomponenten zu verwalten.</p>
    </div>
    <div class="col-lg-5">
        <h3>Komponenten</h3>
        <ul>
          <li>Überschrift</li>
          <li>Text (Editor: MarkItUp / Redactor 2)</li>
        </ul>
    </div>
  </div>

</div>
