<div class="container-fluid">
  <div class="row">
    <div class="col-lg-7">
    <b>Text und Accordion</b>
     <hr/>
     <p>Dieses Modul ermöglicht es einen Text einzugeben und z.B.: eine FAQ Liste anzulegen.
    </div>
    <div class="col-lg-5">
        <b>Benutze Fragmente</b>
        <hr/>
        <ul>
            <li>Accordion
                <ul>
                    <li>accordion_input</li>
                    <li>accordion_output</li>
                </ul>
            </li>
            <li>Textarea
                <ul>
                    <li>textarea_input</li>
                    <li>textarea_output</li>
                </ul>
            </li>
        </ul>
    </div>
  </div>
</div>
